[package]
name = "compose"
version = "0.1.0"
authors = ["Gabe Parmer <gparmer@gwu.edu>"]

[dependencies]
xmas-elf = "0.6.0"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
tar = "0.4"
itertools = "0.8.0"
shell-words = "1.0.0"
petgraph = "0.6.5"
ascent = "*"
