[system]
description = "Simplest system with both capability manager and scheduler, from unit_schedcomp.sh"

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}, {interface = "addr"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "capmgr"
img  = "capmgr.simple"
deps = [{srv = "booter", interface = "init"}, {srv = "booter", interface = "addr"}]
implements = [{interface = "capmgr"}, {interface = "init"}, {interface = "memmgr"}, {interface = "capmgr_create"}]
constructor = "booter"

[[components]]
name = "sched"
img  = "sched.pfprr_quantum_static"
constants = [{variable = "NUM_CPU", value = "4"}]
deps = [{srv = "capmgr", interface = "init"}, {srv = "capmgr", interface = "capmgr"}, {srv = "capmgr", interface = "memmgr"}]
implements = [{interface = "sched"}, {interface = "init"}]
constructor = "booter"

[[components]]
name = "schedtest"
img  = "tests.unit_schedcomp"
constants = [{variable = "NUM_CPU", value = "4"}]
deps = [{srv = "sched", interface = "init"}, {srv = "sched", interface = "sched"}, {srv = "capmgr", interface = "capmgr_create"}]
constructor = "booter"

[[components]]
name = "ping"
img  = "tests.unit_pingpong"
constants = [{variable = "NUM_CPU", value = "4"}]
deps = [{srv = "pong", interface = "pong"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "pong"
img  = "pong.pingpong"
constants = [{variable = "NUM_CPU", value = "4"}]
deps = [{srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
implements = [{interface = "pong"}]
constructor = "booter"

