[system]
description = "Simplest system with both capability manager and scheduler, from unit_schedcomp.sh"

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}, {interface = "addr"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "capmgr"
img  = "capmgr.simple"
deps = [{srv = "booter", interface = "init"}, {srv = "booter", interface = "addr"}]
implements = [{interface = "capmgr"}, {interface = "init"}, {interface = "memmgr"}, {interface = "capmgr_create"}]
constructor = "booter"

[[components]]
name = "sched"
img  = "sched.pfprr_quantum_static"
constants = [{variable = "MAX_NUM_STATIC_THD_COMP", value = "2"}]
deps = [{srv = "capmgr", interface = "init"}, {srv = "capmgr", interface = "capmgr"}, {srv = "capmgr", interface = "memmgr"}]
implements = [{interface = "sched"}, {interface = "init"}]
constructor = "booter"

[[components]]
name = "clientcomp"
constants = [{variable = "MAX_NUM_STATIC_THD_COMP", value = "2"}]
img  = "tests.unit_static_thds"
deps = [{srv = "sched", interface = "init"}, {srv = "sched", interface = "sched"}, {srv = "capmgr", interface = "capmgr_create"}]
constructor = "booter"
virt_res = [
    {vr_type = "sched", instances = [
        {static_hi = {access = ["write", "dynamic_alloc", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "dynamic_alloc", "read", "blocking"], name = "name_static_lo"}}]}
]

[[virt_resources]]
server = "sched"
vr_type = "sched"
resources = [
    {instance = "static_hi", param = {core = "0", priority = "3"}},
    {instance = "static_lo", param = {core = "2", priority = "4"}}
]